version: '3.3'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer-data:/data
    networks:
      - agent-network
      - traefik-network
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.enable: "true"
        traefik.http.middlewares.http2https.redirectscheme.scheme: "https"
        traefik.http.routers.portainer_http.rule: "Host(`portainer.example.com`)"
        traefik.http.routers.portainer_http.entrypoints: "web"
        traefik.http.routers.portainer_http.middlewares: "http2https"
        traefik.http.routers.portainer_https.rule: "Host(`portainer.example.com`)"
        traefik.http.routers.portainer_https.entrypoints: "websecure"
        traefik.http.routers.portainer_https.tls.domains[0].main: "*.example.com"
        traefik.http.routers.portainer_https.tls.certresolver: "example"
        traefik.http.services.portainer-svc.loadbalancer.server.port: 9000


networks:
  agent-network:
    attachable: true
  traefik-network:
    external: true

volumes:
  portainer-data:
