version: '3.7'

services:
  traefik:
    image: traefik:2.1
    environment:
      - GANDIV5_API_KEY_FILE=/run/secrets/gandiv5-api-key
    ports:
      - 80:80
      - 443:443
    command:
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-network"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.example.acme.dnsChallenge.provider=gandiv5"
      - "--certificatesresolvers.example.acme.email=user@email.com"
      - "--certificatesresolvers.example.acme.storage=/acme.json"
    networks:
      - default
      - traefik-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik/acme.json:/acme.json
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager

networks:
  traefik-network:
    external: true

